#!/bin/bash
 
error() {
  echo "$1" 1>&2
  exit 1
}
 
#####################
# main functions
#--------------------
 
gen_main_configure() {
 
main_template="
###################################################################
# Notice: Please don't modify this file. It's generated by scripts. ($0 -f $@)
#------------------------------------------------------------------
 
ddns-update-style none;
#default-lease-time 7200;         #two hours;
default-lease-time 14400;
#max-lease-time 14400;             #four hours;
max-lease-time 28800;
log-facility local7;
 
subnet 192.168.1.0 netmask 255.255.255.0 {
  range 192.168.1.10 192.168.1.250;
  option routers 192.168.1.1;
  option subnet-mask 255.255.255.0;
  option broadcast-address 192.168.1.255;
  option domain-name-servers 202.130.97.66,8.8.8.8;
  allow unknown-clients;
}
 
$hosts_info
"
printf "%s" "$main_template"
}
 
gen_host_configure() {
hosts_template="
host $hostname { hardware ethernet $host_eth; fixed-address $host_ip; }
"
printf "%s" "$hosts_template"
}
 
read_hosts() {
  #dns-server,00:1a:4d:0f:c0:c0,192.168.1.153
  for list in `cat $1 | grep -v "^#"`  
  do
    #echo $list
    hostname=`echo $list | cut -d , -f 1`
    host_eth=`echo $list | cut -d , -f 2`
    host_ip=`echo $list | cut -d , -f 3`
    gen_host_configure
  done
}
 
gen_configure() {
  conf="/etc/dhcp/dhcpd.conf"
  hosts_info=`read_hosts $1`
  #echo $hosts_info
  if [ -f $conf ]
  then
    gen_main_configure $1 | tee $conf
    service isc-dhcp-server restart
  else
    gen_main_configure $1
  fi
}
 
#####################
# 
#--------------------
 
case $1 in
-f)
  [ -f $2 ] && gen_configure $2 || error "File $2 doesn't exist."
;;
*)
  error "./$0 -f hosts_info.txt"
esac
